version: '{build}'

environment:
  CHOCO_API_KEY:
    secure: hsyCpvNm18kiTWHdcPSN7PLra8FGfypgnSuviKQMBdY1LGnpjE4//JD1uQ+vnzU5

build_script:
  - choco pack

test_script:
  - choco install metanorma -dv -s "'.;https://chocolatey.org/api/v2/'"
  - refreshenv
  - metanorma --help
  - git clone https://github.com/riboseinc/unece-cefact-recommendation-42.git & cd unece-cefact-recommendation-42
  - set PATH=c:\tools\ruby25\bin;%PATH% # make lookup ruby25 before preinstalled one
  - call make -f Makefile.win clean all

deploy_script:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") {
        choco apikey -k $Env:CHOCO_API_KEY -source https://chocolatey.org/
        choco push metanorma.*.nupkg -s https://chocolatey.org/
      } else {
        Write-Host Skip deployment for non tag commits
      }

on_finish:
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\unece-cefact-recommendation-42.*
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\images
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\reference-docs
  - ps: Push-AppveyorArtifact C:\ProgramData\chocolatey\logs\chocolatey.log
  - ps: Push-AppveyorArtifact $Env:APPVEYOR_BUILD_FOLDER\unece-cefact-recommendation-42.zip