version: '{build}'

environment:
  CHOCO_API_KEY:
    secure: hsyCpvNm18kiTWHdcPSN7PLra8FGfypgnSuviKQMBdY1LGnpjE4//JD1uQ+vnzU5

build_script:
  - choco pack

test_script:
  - choco install metanorma -dv -s "'.;https://chocolatey.org/api/v2/'"
  - refreshenv
  - metanorma --help

deploy_script:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") {
        choco apikey -k $Env:CHOCO_API_KEY -source https://chocolatey.org/
        choco push metanorma.*.nupkg -s https://chocolatey.org/
      } else {
        Write-Host Skip deployment for non tag commits
      }

on_finish:
  - ps: Push-AppveyorArtifact C:\ProgramData\chocolatey\logs\chocolatey.log
  - ps: Push-AppveyorArtifact C:\Tools\ruby25\lib\ruby\gems\2.5.0\extensions\x64-mingw32\2.5.0\ruby-xslt-0.9.10\mkmf.log