version: '{build}'

environment:
  CHOCO_API_KEY:
    secure: hsyCpvNm18kiTWHdcPSN7PLra8FGfypgnSuviKQMBdY1LGnpjE4//JD1uQ+vnzU5

build_script:
  - choco pack

test_script:
  - choco install -y msys2 --params "/NoUpdate"
  - refreshenv
  - choco install metanorma -dv -s "'.;https://chocolatey.org/api/v2/'"
  - choco install -y git make gnuwin32-coreutils.portable sed
  - refreshenv
  - metanorma --help
  - git clone https://github.com/riboseinc/unece-cefact-recommendation-42.git & cd unece-cefact-recommendation-42
  - set PATH=c:\tools\ruby25\bin;%PATH% # make lookup ruby25 before preinstalled one
  - gem install bundler -v 1.17.3
  - call make -f Makefile.win clean all
  - choco uninstall metanorma -y

deploy_script:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") {
        $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
        $pkgVersion = Select-Xml -Path $Env:APPVEYOR_BUILD_FOLDER\metanorma.nuspec `
             -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
             -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
        choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
        choco push $Env:APPVEYOR_BUILD_FOLDER\metanorma.${pkgVersion}.nupkg -source https://chocolatey.org/
      } else {
        Write-Host Skip deployment for non tag commits
      }

on_finish:
  - ps: Push-AppveyorArtifact C:\ProgramData\chocolatey\logs\chocolatey.log
  - ps: Push-AppveyorArtifact C:\Tools\ruby25\lib\ruby\gems\2.5.0\extensions\x64-mingw32\2.5.0\ruby-xslt-0.9.10\mkmf.log
  - ps: Push-AppveyorArtifact C:\Tools\ruby25\lib\ruby\gems\2.5.0\extensions\x64-mingw32\2.5.0\ruby-xslt-0.9.10\gem_make.out
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\unece-cefact-recommendation-42.*
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\images
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\reference-docs
  - ps: Push-AppveyorArtifact $Env:APPVEYOR_BUILD_FOLDER\unece-cefact-recommendation-42.zip
