name: main

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Build chocolatey package
        run: choco pack
      - name: Find package path
        id: findnupkg
        shell: cmd
        run: |
          FOR /F "tokens=*" %%g IN ('powershell -noprofile "ls metanorma.*.nupkg | ForEach-Object {$_.FullName}"') do (SET NUPKG=%%g)
          echo ##[set-output name=nupkg;]%NUPKG%
      - uses: actions/upload-artifact@master
        with:
          name: nupkg
          path: ${{ steps.findnupkg.outputs.nupkg }}
  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: nupkg
      - name: Install chocolatey package
        shell: cmd
        run: |
          move nupkg\*.nupkg .\
          choco install --no-progress metanorma -dv -s "'.;https://chocolatey.org/api/v2/'"
          refreshenv
      - name: Test metanorma & dependencies
        shell: cmd
        run: |
          call RefreshEnv.cmd
          where xml2rfc
          where metanorma
          metanorma help
      - name: Test compilation
        env:
          GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
        shell: cmd
        run: |
          for %%f in (iso cc gb iec itu ogc un) do (
            git clone https://%GITHUB_CREDENTIALS%@github.com/metanorma/mn-samples-%%f.git
            pushd mn-samples-%%f
            call rm Gemfile
            call metanorma site generate . -c metanorma.yml --agree-to-terms
            popd
          )
      - name: Uninstall chocolatey package
        shell: pwsh
        run: |
          choco uninstall metanorma -y
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        with:
          name: nupkg
      - name: Push to chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
          $pkgVersion = Select-Xml -Path metanorma.nuspec `
               -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
               -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
          choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
          choco push metanorma.${pkgVersion}.nupkg -source https://chocolatey.org/
