name: main

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - run: choco pack

      - uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: metanorma.*.nupkg
  test-docker:
    runs-on: windows-2019 # must match to test/Dockerfile image
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: nupkg
          path: test

      - run: docker build -t metanorma-test .
        working-directory: test

      - run: docker run -e GIT_CREDS metanorma-test iso cc iec itu ogc un
        env:
          GIT_CREDS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: nupkg

      - run: choco install --no-progress metanorma -dv -s "'.;https://chocolatey.org/api/v2/'"

      - name: Test dependencies
        shell: cmd
        run: |
          call RefreshEnv.cmd
          where xml2rfc
          where metanorma
          where dot

      - run: metanorma help

      - run: .\test\test.ps1 iso cc iec itu ogc un
        env:
          GIT_CREDS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"

      - run: choco uninstall metanorma -y
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: nupkg

      - name: Push to chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
          $pkgVersion = Select-Xml -Path metanorma.nuspec `
               -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
               -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
          choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
          choco push metanorma.${pkgVersion}.nupkg -source https://chocolatey.org/
