name: main

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - run: choco pack

      - uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: metanorma.*.nupkg
  test-docker:
    runs-on: windows-2019 # must match to test/Dockerfile image
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: nupkg
          path: test

      - run: docker build -t metanorma-test -f Dockerfile --secret id=GIT_CREDENTIALS,target=git_creds .
        env:
          GIT_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
        working-directory: test
  test:
    runs-on: windows-latest
    needs: build
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: nupkg

      - name: Install chocolatey package
        shell: cmd
        run: |
          move nupkg\*.nupkg .\
          choco install --no-progress metanorma -dv -s "'.;https://chocolatey.org/api/v2/'"
          refreshenv

      - name: Test metanorma & dependencies
        shell: cmd
        run: |
          call RefreshEnv.cmd
          where xml2rfc
          where metanorma
          metanorma help

      - name: Test compilation
        env:
          GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
        shell: cmd
        run: |
          for %%f in (iso cc gb iec itu ogc un) do (
            git clone https://%GITHUB_CREDENTIALS%@github.com/metanorma/mn-samples-%%f.git
            pushd mn-samples-%%f
            call rm Gemfile
            call metanorma site generate . -c metanorma.yml --agree-to-terms
            popd
          )

      - name: Uninstall chocolatey package
        shell: pwsh
        run: choco uninstall metanorma -y
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: nupkg

      - name: Push to chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
          $pkgVersion = Select-Xml -Path metanorma.nuspec `
               -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
               -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
          choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
          choco push metanorma.${pkgVersion}.nupkg -source https://chocolatey.org/
