name: main

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build-matrix:
    name: Matrix
    uses: metanorma/ci/.github/workflows/build-sample-matrix.yml@main
    with:
      smoke: false
      flavors-only: true
      public-only: true

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: choco pack

      - uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: metanorma.*.nupkg

      # Test the package installation and verify metanorma executable
      - name: Test package installation
        run: |
          # Install the package from local source
          choco install --no-progress metanorma -dv -y -s "'.;chocolatey'"

          # Verify metanorma executable is available
          if (Get-Command "metanorma" -ErrorAction SilentlyContinue) {
            Write-Host "[OK] metanorma executable found"
            metanorma version
          } else {
            Write-Error "[ERROR] metanorma executable not found in PATH"
            exit 1
          }

          # Verify xml2rfc is available (required for IETF support)
          if (Get-Command "xml2rfc" -ErrorAction SilentlyContinue) {
            Write-Host "[OK] xml2rfc executable found"
            xml2rfc --version
          } else {
            Write-Error "[ERROR] xml2rfc executable not found - IETF support requires xml2rfc"
            exit 1
          }
        shell: powershell

  test-scripts:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test installation/uninstallation scripts
        run: |
          # Run comprehensive test suite
          pwsh -ExecutionPolicy Bypass -File test/test_installation.ps1 -Verbose
        shell: powershell

  test-docker:
    runs-on: windows-2022 # must match to test/Dockerfile image
    needs: [build, build-matrix]

    concurrency:
      group: 'test-docker-${{ github.workflow }}-${{ github.job }}-${{ matrix.flavor.id }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.flavor.experimental }}
    strategy:
      max-parallel: 5
      fail-fast: true
      matrix: # ${{ fromJson(needs.build-matrix.outputs.samples-matrix) }}
        flavor: # https://github.com/metanorma/chocolatey-metanorma/issues/73
          - id: iso
            experimental: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: test

      # unfortunatelly windows docker image too big to prebuild it once
      - run: docker build -t metanorma-docker-test .
        working-directory: test

      - run: docker image inspect metanorma-docker-test

      - run: |
          echo "call docker run metanorma-docker-test metanorma %*" > ./metanorma.cmd
          chmod +x ./metanorma.cmd
          echo "$(pwd)" >> $GITHUB_PATH
        shell: bash

      - name: Fetch samples (${{ matrix.flavor.id }})
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: metanorma/mn-samples-${{ matrix.flavor.id }}
          path: ${{ matrix.flavor.id }}
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          fetch-depth: 1

      - uses: actions-mn/site-gen@main
        with:
          agree-to-terms: true
          source-path: ${{ matrix.flavor.id }}

  test:
    runs-on: windows-latest
    needs: [build, build-matrix]

    concurrency:
      group: 'test-${{ github.workflow }}-${{ github.job }}-${{ matrix.flavor.id }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.flavor.experimental }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.samples-matrix) }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nupkg

      # workaround for https://github.com/chocolatey/choco/issues/1691
      - run: |
          set +e
          if ! choco install --no-progress -pre metanorma -dv -s "'.;chocolatey'" > choco.install.log 2>&1; then
            cat choco.install.log
            if grep -q " - git\.install (exited 1)" choco.install.log; then
              echo "Git installation failed. Ignoring the error."
              choco install --ignore-dependencies --no-progress -pre metanorma -dv -s "'.;chocolatey'"
              exit 0
            else
              exit 1
            fi
          fi
        shell: bash

      - name: Fetch samples (${{ matrix.flavor.id }})
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: metanorma/mn-samples-${{ matrix.flavor.id }}
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          fetch-depth: 1

      - uses: actions-mn/site-gen@main
        with:
          agree-to-terms: true

      - run: choco uninstall metanorma -y

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: [test, test-scripts]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: nupkg

      - name: Push to chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
          $pkgVersion = Select-Xml -Path metanorma.nuspec `
               -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
               -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
          choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
          choco push metanorma.${pkgVersion}.nupkg -source https://chocolatey.org/
