name: main

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build-matrix:
    name: Matrix
    uses: metanorma/ci/.github/workflows/build-sample-matrix.yml@main
    with:
      smoke: false
      flavors-only: true
      public-only: true

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - run: choco pack

      - uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: metanorma.*.nupkg

  test-docker:
    runs-on: windows-2019 # must match to test/Dockerfile image
    needs: [build, build-matrix]

    concurrency:
      group: 'test-docker-${{ github.workflow }}-${{ github.job }}-${{ matrix.flavor.id }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.flavor.experimental }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.samples-matrix) }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: nupkg
          path: test

      - run: docker build -t metanorma-test .
        working-directory: test

      - run: |
          echo "call docker run -e GIT_CREDS metanorma-test %*" > ../metanorma.cmd
        env:
          GIT_CREDS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"

      - name: Fetch samples (${{ matrix.flavor.id }})
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: metanorma/mn-samples-${{ matrix.flavor.id }}
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          fetch-depth: 1

      - uses: actions-mn/site-gen@v1
        with:
          agree-to-terms: true

  test:
    runs-on: windows-latest
    needs: [build, build-matrix]

    concurrency:
      group: '${{ github.workflow }}-${{ github.job }}-${{ matrix.flavor.id }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.flavor.experimental }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.samples-matrix) }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nupkg

      - run: choco install --no-progress -pre metanorma -dv -s "'.;chocolatey'"

      - name: Test dependencies
        shell: cmd
        run: |
          call RefreshEnv.cmd
          where xml2rfc
          where metanorma
          where dot

      - name: Fetch samples (${{ matrix.flavor.id }})
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: metanorma/mn-samples-${{ matrix.flavor.id }}
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          fetch-depth: 1

      - uses: actions-mn/site-gen@v1
        with:
          agree-to-terms: true

      - run: choco uninstall metanorma -y

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: nupkg

      - name: Push to chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          $namespaces = @{nuspec = "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd"}
          $pkgVersion = Select-Xml -Path metanorma.nuspec `
               -XPath "/nuspec:package/nuspec:metadata/nuspec:version/text()" `
               -Namespace $namespaces | Select-Object -Expand Node | Select-Object -Expand Data
          choco apikey -key $Env:CHOCO_API_KEY -source https://chocolatey.org/
          choco push metanorma.${pkgVersion}.nupkg -source https://chocolatey.org/
