name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/packed-mn ]
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Add writable remote
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"

    - name: Install xmllint
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libxml2-utils

    # - uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: '3.4'

    - name: Parse metanorma-cli version
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref || github.event.inputs.next_version }}
        GH_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
      run: |
        gh api repos/metanorma/metanorma-build-scripts/contents/gemver-to-semver.rb --jq '.content' | base64 -d > gemver-to-semver.rb && chmod +x gemver-to-semver.rb
        echo "PACKAGE_VERSION=$(./gemver-to-semver.rb --chocolatey ${METANORMA_CLI_TAG})" >> $GITHUB_ENV

    - name: Update metanorma.nuspec
      run: |
        CURRENT_YEAR=$(date +%Y)
        xmllint --shell metanorma.nuspec << EOF
        setns ns=http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd
        cd /ns:package/ns:metadata/ns:version
        set ${PACKAGE_VERSION}
        cd /ns:package/ns:metadata/ns:copyright
        set ${CURRENT_YEAR} Ribose Inc.
        save
        exit
        EOF

    - name: Prepare URL and SHA256 files
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref || github.event.inputs.next_version }}
        GH_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
      run: |
        # Extract tag name from METANORMA_CLI_TAG for gh release download
        TAG_NAME=$(echo "${METANORMA_CLI_TAG}" | sed 's|refs/tags/||')
        METANORMA_EXE_URL="https://github.com/metanorma/packed-mn/releases/download/${TAG_NAME}/metanorma-windows-x86_64.exe"
        echo "${METANORMA_EXE_URL}" > tools/metanorma.url.txt
        gh release download "${TAG_NAME}" --repo metanorma/packed-mn --pattern "metanorma-windows-x86_64.exe" --output /tmp/metanorma-windows-x86_64.exe
        sha256sum /tmp/metanorma-windows-x86_64.exe | cut -d ' ' -f 1 > tools/metanorma.sha256.txt
        rm /tmp/metanorma-windows-x86_64.exe
        echo "Metanorma URL: $(cat tools/metanorma.url.txt) SHA265: $(cat tools/metanorma.sha256.txt)"

    - name: Push commit and tag
      run: |
        git add metanorma.nuspec
        git add tools/metanorma.sha256.txt
        git add tools/metanorma.url.txt
        git commit -m "Bump version to ${PACKAGE_VERSION}"
        git tag "v${PACKAGE_VERSION}"
        git push origin HEAD:${GITHUB_REF} --tags
