name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/packed-mn ]
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'

jobs:
  push-tag:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Add writable remote
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"

    - name: Install xmllint
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libxml2-utils

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Parse metanorma-cli version
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref || github.event.inputs.next_version }}
      run: |
        curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/main/gemver-to-semver.rb && chmod +x gemver-to-semver.rb
        echo "PACKAGE_VERSION=$(./gemver-to-semver.rb ${METANORMA_CLI_TAG})" >> $GITHUB_ENV

    - name: Update metanorma.nuspec
      run: |
        xmllint --shell metanorma.nuspec << EOF
        setns ns=http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd
        cd /ns:package/ns:metadata/ns:version
        set ${PACKAGE_VERSION}
        save
        exit
        EOF

    - name: Update sha256
      run: |
        curl -s "https://github.com/metanorma/packed-mn/releases/download/v${PACKAGE_VERSION}/metanorma-windows-x64.exe" | sha256sum | cut -d ' ' -f 1 > tools/metanorma.sha256

    - name: Push commit and tag
      run: |
        git add metanorma.nuspec
        git add tools/metanorma.sha256
        git commit -m "Bump version to ${PACKAGE_VERSION}"
        git tag v${PACKAGE_VERSION}
        git push origin HEAD:${GITHUB_REF} --tags
