name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/packed-mn ]

jobs:
  push-tag:
    runs-on: ubuntu-18.04
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v1
    - name: Add writable remote
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
        git remote add github "https://metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
    - name: Install xmllint
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libxml2-utils
    - name: Parse metanorma-cli version
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref }}
      shell: python
      run: |
        import os

        version = os.environ.get("METANORMA_CLI_TAG")[len('refs/tags/v'):]
        matches = re.search(r"[-\.]*(?P<suffix>[^\d\W]+)$", version)

        if matches:
          version = version.replace(matches.group(0), f"-{matches.group(1)}")

        print(f"::set-env name=PACKAGE_VERSION::{version}")
    - name: Update metanorma.nuspec
      run: |
        xmllint --shell metanorma.nuspec << EOF
        setns ns=http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd
        cd /ns:package/ns:metadata/ns:version
        set ${PACKAGE_VERSION}
        save
        exit
        EOF
    - name: Push commit and tag
      run: |
        git add metanorma.nuspec
        git commit -m "Bump version to ${PACKAGE_VERSION}"
        git tag v${PACKAGE_VERSION}
        git push github HEAD:${GITHUB_REF} --tags
